// <auto-generated />
using System;
using HousingSolutions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HousingSolutions.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021001719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HousingSolutions.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2025, 10, 21, 6, 17, 19, 247, DateTimeKind.Local).AddTicks(1731),
                            ResidentName = "Resident 1",
                            StartTime = new DateTime(2025, 10, 21, 3, 17, 19, 245, DateTimeKind.Local).AddTicks(4546)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new DateTime(2025, 10, 21, 10, 17, 19, 247, DateTimeKind.Local).AddTicks(2067),
                            ResidentName = "Resident 1",
                            StartTime = new DateTime(2025, 10, 21, 7, 17, 19, 247, DateTimeKind.Local).AddTicks(2063)
                        });
                });

            modelBuilder.Entity("HousingSolutions.Domain.Entities.Door", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLocked = true,
                            Name = "Main Entrance"
                        },
                        new
                        {
                            Id = 2,
                            IsLocked = false,
                            Name = "Garage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
